### ISSUE TITLE
Port monitor throws NullPointerException

### ISSUE THREAD

**Issue by taylor8294** [summitt/Nope-Proxy#74]
Using

- burpsuite_pro_v2023.12.1.5.jar
- NoPE Proxy version 1.5.2
- Windows 11 Home (Version 10.0.22631 Build 22631, os.arch amd64)
- Java SDK 21 installed
- Java SE 8 installed
- NCAP 1.79 installed in winpcap compatability mode
- Wireshark version 4.2.3 installed.

I have configured Burp proxy, NoPE DNS Server Config correctly so that I see DNS history coming in, but clicking the green play icon to start the port monitor nothing shows in the results, and the following error message is logged in Std Out

```
MLog initialization issue: slf4j found no binding or threatened to use its (dangerously silent) NOPLogger. We consider the slf4j library not found.
Lister Started
java.lang.NullPointerException: Cannot invoke "org.pcap4j.packet.TcpPacket.getHeader()" because "tcp" is null
        at josh.utils.Lister$1.gotPacket(Lister.java:70)
        at org.pcap4j.core.PcapHandle$GotPacketFuncExecutor.lambda$got_packet$0(PcapHandle.java:1254)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by LeeDiay** [comment]
i have the same issues! did you fixed it?
